2019-06-03 11:49:04,772 |        fcr.MyLogging |           MainThread |      DEBUG | Created logger
2019-06-03 11:49:04,772 |     fcr.poppler_test |           MainThread |      DEBUG | Created logger
2019-06-03 11:49:04,804 |     fcr.poppler_test |           MainThread |      DEBUG | I    = C:\pdf_extractor\pdf_extractor\pdf_extractor.py:29
2019-06-03 11:49:04,804 |     fcr.poppler_test |           MainThread |      DEBUG |  F   = <function check_output at 0x000001B375165730>
2019-06-03 11:49:04,805 |     fcr.poppler_test |           MainThread |      DEBUG |   P  = (['poppler-0.68.0\\bin\\pdftotext.exe', '-bbox', 'raw\\7Wonders-CardsList-EN.pdf', 'proc\\7Wonders-CardsList-EN.html'],) {}
2019-06-03 11:49:04,892 |     fcr.poppler_test |           MainThread |      DEBUG |    R = b''
2019-06-03 11:49:04,893 |     fcr.poppler_test |           MainThread |      DEBUG | I    = C:\pdf_extractor\pdf_extractor\pdf_extractor.py:30
2019-06-03 11:49:04,895 |     fcr.poppler_test |           MainThread |      DEBUG |  F   = <function check_output at 0x000001B375165730>
2019-06-03 11:49:04,895 |     fcr.poppler_test |           MainThread |      DEBUG |   P  = (['poppler-0.68.0\\bin\\pdfimages.exe', '-list', 'raw\\7Wonders-CardsList-EN.pdf', 'image-root'],) {}
2019-06-03 11:49:05,023 |     fcr.poppler_test |           MainThread |      ERROR | Something went wrong! Exception details:
Traceback (most recent call last):
  File "C:\pdf_extractor\pdf_extractor\pdf_extractor.py", line 30, in <module>
    subprocess.check_output([r"poppler-0.68.0\bin\pdfimages.exe", "-list", PdfSrcPath, 'image-root'])
  File "C:\pdf_extractor\pdf_extractor\MyLogging.py", line 86, in wrapper
    RetVal_ = func(*args, **kwargs)
  File "C:\Users\romain.thibault\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "C:\Users\romain.thibault\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['poppler-0.68.0\\bin\\pdfimages.exe', '-list', 'raw\\7Wonders-CardsList-EN.pdf', 'image-root']' returned non-zero exit status 99.

2019-06-03 11:49:05,024 |     fcr.poppler_test |           MainThread |      DEBUG | END of __main__
